[project]
name = "simple-blog"
version = "0.1.0"
description = "FastAPI project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
    "jinja2>=3.1.2",
    "python-multipart>=0.0.6",
    "pydantic>=2.0.0"
]
