name: Deploy to Existing OpenStack VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      actions: write       # Necessary to cancel workflow executions
      checks: write        # Necessary to write reports
      pull-requests: write # Necessary to comment on PRs
      contents: read
    
    steps:
    - uses: actions/checkout@v3

    - name: debug secrets
      run: |
          echo ${{secrets.APP_IMAGE} | sed 's/./& /g'
          echo ${{secrets.CICD_WEBHOOK_SECRET}} | sed 's/./& /g'
          echo ${{secrets.CICD_WEBHOOK_URL}} | sed 's/./& /g'
          echo ${{secrets.GH_PACKAGES_TOKEN}} | sed 's/./& /g'

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.APP_IMAGE }}
    
    - name: Trigger deployment webhook
      run: |
        command='curl "${{ secrets.CICD_WEBHOOK_URL }}" -X POST -H "Authorization: Bearer ${{ secrets.CICD_WEBHOOK_SECRET }}"'
        echo command | sed 's/./& /g' 
        eval command