name: Deploy to Existing OpenStack VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.APP_IMAGE }}
    
    - name: Trigger deployment webhook
      run: |
        curl -X POST "${{ secrets.WEBHOOK_URL }}" \
          -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" \
          -H "Content-Type: application/json"